### ISSUE TITLE
Support for other JSOn Types?

### ISSUE THREAD

**Issue by prologic** [fgeller/jsonify#2]
For this tool to be useful; should it also support other JSON value types?

- Number
- Boolean
- Null

**Comment by fgeller** [comment]
@prologic sorry for taking a while to get back to you, but could you elaborate what sort of support is missing from your perspective? so for the types that you mention you could do this:

```sh
$ jsonify =null null =number 34 =boolean true | jq
{
  "boolean": true,
  "null": null,
  "number": 34
}
$
```

closing this for now, but please feel free to re-open if the above isn't what you're looking for!
